apiVersion: v2
name: zookeeper
description: Zookeeper Helm chart for Kubernetes
version: 0.2.12
appVersion: 0.2.12
keywords:
- zookeeper
- storage
home: https://github.com/apache/zookeeper
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
